{
 "title": "BigBlueButton Universe",
 "tags": [
  "BigBlueButton",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(bbb_exporter, job)"
    }
   },
   {
    "name": "job_node_exporter",
    "label": "Job node_exporter",
    "query": {
     "query": "label_values(node_cpu_seconds_total, job)"
    }
   },
   {
    "name": "job_netdata",
    "label": "Job Netdata",
    "query": {
     "query": "label_values(netdata_system_cpu_percentage_average, job)"
    }
   },
   {
    "name": "interface",
    "label": "Network Interface",
    "query": {
     "query": "label_values(node_network_address_assign_type, device)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bbb_api_up{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of participants (current)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bbb_meetings_participants{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Number of participants",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 4 },
   "targets": [
    {
     "expr": "sum(bbb_meetings_participants{job=\"$job\"})",
     "legendFormat": "Amount"
    }
   ]
  },
  {
   "title": "Number of participants - per server (current)",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bbb_meetings_participants{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of rooms (current)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bbb_room_participants_gcount{job=\"$job\"})"
    },
    {}
   ]
  },
  {
   "title": "Number of rooms",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 11 },
   "targets": [
    {
     "expr": "sum(bbb_room_participants_gcount{job=\"$job\"})",
     "legendFormat": "Amount"
    }
   ]
  },
  {
   "title": "Number of rooms - per server (current)",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bbb_room_participants_gcount{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(bbb_meetings_participants_origin{job=\"$job\"}) by  (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Video",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(bbb_meetings_video_participants{job=\"$job\"})",
     "legendFormat": "Cam"
    }
   ]
  },
  {
   "title": "Microphone connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(bbb_meetings_voice_participants{job=\"$job\"})",
     "legendFormat": "Voice"
    }
   ]
  },
  {
   "title": "Network Utilization - public interface",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "Kbits", "label": "Bandwidth" }
   ],
   "targets": [
    {
     "expr": "sum(abs(netdata_net_net_kilobits_persec_average{job=\"$job_netdata\", family=\"enp175s0f1np1\"})) by (dimension)",
     "legendFormat": " {{dimension}}"
    },
    {
     "expr": "sum(bbb_meetings_participants{job=\"$job\"})",
     "legendFormat": "Participants"
    }
   ]
  },
  {
   "title": "System details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Video Participants",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short", "label": "Participants" }
     ],
     "targets": [
      {
       "expr": "bbb_meetings_video_participants{job=\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Participants",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short", "label": "Participants" }
     ],
     "targets": [
      {
       "expr": "bbb_meetings_participants{job=\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Voice Participants",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short", "label": "Participants" }
     ],
     "targets": [
      {
       "expr": "bbb_meetings_voice_participants{job=\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Number of Rooms",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Rooms" }
     ],
     "targets": [
      {
       "expr": "bbb_room_participants_gcount{job=\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Participants Origin",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short", "label": "Participants" }
     ],
     "targets": [
      {
       "expr": "bbb_meetings_participants_origin{job=\"$job\"}",
       "legendFormat": "{{instance}} - {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Server details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utlization ",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "percent", "label": "CPU Utlization [%]" }
     ],
     "targets": [
      {
       "expr": "(1 - avg(irate(node_cpu_seconds_total{mode=\"idle\", job=\"$job_node_exporter\"}[5m])) by (instance)) * 100",
       "legendFormat": "{{instance}} "
      },
      {
       "expr": "sum(netdata_system_cpu_percentage_average{dimension!=\"idle\", job=\"$job_netdata\"}) by (instance)",
       "legendFormat": "{{instance}} "
      }
     ]
    },
    {
     "title": "Memory Utilization (RAM)",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(netdata_system_ram_MiB_average{job=\"$job_netdata\"}) by (instance) - sum(netdata_mem_available_MiB_average{job=\"$job_netdata\"}) by (instance)) / 1024 * 10",
       "legendFormat": "{{instance}} "
      }
     ]
    },
    {
     "title": "Disk usage (%)",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(100 / sum(netdata_disk_space_GiB_average{dimension=\"avail\",family=\"/\",job=\"bbb_prod_netdata\"}) by (instance)) * sum(netdata_disk_space_GiB_average{dimension=\"used\",family=\"/\",job=\"bbb_prod_netdata\"} ) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Network - received data",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "Kbits" }
     ],
     "targets": [
      {
       "expr": "abs(netdata_net_net_kilobits_persec_average{job=\"$job_netdata\", family=\"enp175s0f1np1\", dimension=\"received\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Network - sent data",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "Kbits" }
     ],
     "targets": [
      {
       "expr": "abs(netdata_net_net_kilobits_persec_average{job=\"$job_netdata\", family=\"enp175s0f1np1\", dimension=\"sent\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "BigBlueButton API Response Time - getMeetings (95th Percentile)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "s", "label": "Resonse Time" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{job=\"$job\", endpoint=\"getMeetings\"}[5m])) by (le, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Metrics Response Time (95th Percentile)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "s", "label": "Response Time" }
     ],
     "targets": [
      {
       "expr": "sum(histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{job=\"$job\"}[5m])) by (le, instance, endpoint, parameters))) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "BigBlueButton Exporter Version",
     "type": "table",
     "gridPos": { "h": 4, "w": 7, "x": 3, "y": 66 },
     "targets": [
      {
       "expr": "bbb_exporter{job=\"$job\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Recordings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Utilization",
     "type": "table",
     "gridPos": { "h": 22, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(node_filesystem_size_bytes{job=\"$job_node_exporter\"} - node_filesystem_avail_bytes{job=\"$job_node_exporter\"}) / node_filesystem_size_bytes{job=\"$job_node_exporter\"}"
      }
     ]
    },
    {
     "title": "Recordings Processing",
     "type": "table",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 45 },
     "targets": [
      {
       "expr": "label_replace(bbb_recordings_processing{job=\"$job\"}, \"name\", \"$1\", \"instance\", \"([a-zA-Z0-9-]*).*:.*\")"
      }
     ]
    },
    {
     "title": "Recordings Unprocessed",
     "type": "table",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 45 },
     "targets": [
      {
       "expr": "label_replace(bbb_recordings_unprocessed{job=\"$job\"}, \"name\", \"$1\", \"instance\", \"([a-zA-Z0-9-]*).*:.*\")"
      }
     ]
    },
    {
     "title": "Recordings Published",
     "type": "table",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 50 },
     "targets": [
      {
       "expr": "label_replace(bbb_recordings_published{job=\"$job\"}, \"name\", \"$1\", \"instance\", \"([a-zA-Z0-9-]*).*:.*\")"
      }
     ]
    },
    {
     "title": "Recordings Deleted",
     "type": "table",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 50 },
     "targets": [
      {
       "expr": "label_replace(bbb_recordings_deleted{job=\"$job\"}, \"name\", \"$1\", \"instance\", \"([a-zA-Z0-9-]*).*:.*\")"
      }
     ]
    },
    {
     "title": "Recordings Unpublished",
     "type": "table",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 55 },
     "targets": [
      {
       "expr": "label_replace(bbb_recordings_unpublished{job=\"$job\"}, \"name\", \"$1\", \"instance\", \"([a-zA-Z0-9-]*).*:.*\")"
      }
     ]
    },
    {
     "title": "Recordings Unprocessed",
     "type": "graph",
     "description": "Requires `RECORDINGS_METRICS_READ_FROM_DISK` to be enabled on the BigBlueButton Exporter",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "short", "label": "Recordings " }
     ],
     "targets": [
      {
       "expr": "bbb_recordings_unprocessed{job=\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Heatmaps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heatmap of Room Participants",
     "type": "heatmap",
     "description": "Buckets (Y axis) represents the number of participants while the count in each bucket represents the number of rooms with that particular bucket's value. ",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "sum by (le) (bbb_room_participants_bucket{job=\"$job\"})",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Heatmap of Listeners Participants",
     "type": "heatmap",
     "description": "Buckets (Y axis) represents the number of listeners while the count in each bucket represents the number of rooms with that particular bucket's value. ",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 46 },
     "targets": [
      {
       "expr": "sum by (le) (bbb_room_listeners_bucket{job=\"$job\"})",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Heatmap of Voice Participants",
     "type": "heatmap",
     "description": "Buckets (Y axis) represents the number of voice participants while the count in each bucket represents the number of rooms with that particular bucket's value. ",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 56 },
     "targets": [
      {
       "expr": "sum by (le) (bbb_room_voice_participants_bucket{job=\"$job\"})",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Heatmap of Video Participants",
     "type": "heatmap",
     "description": "Buckets (Y axis) represents the number of video participants while the count in each bucket represents the number of rooms with that particular bucket's value. ",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 56 },
     "targets": [
      {
       "expr": "sum by (le) (bbb_room_video_participants_bucket{job=\"$job\"})",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}